#!/bin/bash
set -eou pipefail

if [[ -z "${1-}" ]]; then
  cargo bench --no-fail-fast --features bench -p xmtp_mls
else
  cargo bench --no-fail-fast --features bench -p xmtp_mls -- "$1"
fi

echo "Open benchmarks at target/criterion/report.html"
