#!/usr/bin/env sh
set -eu

# Check if x86_64-linux-gnu-gcc is installed AND that the user is on a mac
if [ ! -x "$(command -v x86_64-linux-gnu-gcc)" ] && [ "$(uname)" = "Darwin" ]; then
    echo "Installing cross compile toolchain"
    brew tap messense/macos-cross-toolchains
    brew install x86_64-unknown-linux-gnu    
fi

rustup target add x86_64-unknown-linux-gnu
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc
cargo build --release --package mls_validation_service --target x86_64-unknown-linux-gnu
mkdir -p .cache
cp -f ./target/x86_64-unknown-linux-gnu/release/mls-validation-service ./.cache/mls-validation-service
docker build --platform=linux/amd64 -t xmtp/mls-validation-service:latest -f ./dev/validation_service/local.Dockerfile .
