#!/bin/bash
set -eou pipefail


if [[ "${OSTYPE}" == "darwin"* ]]; then
  if ! which inferno-flamegraph &>/dev/null; then cargo install inferno; fi
fi

if [[ -z "${1-}" ]]; then
  XMTP_FLAMEGRAPH=trace cargo bench --no-fail-fast --features bench -p xmtp_mls
else
  XMTP_FLAMEGRAPH=trace cargo bench --no-fail-fast --features bench -p xmtp_mls -- "$1"
fi

cat xmtp_mls/tracing.foldeed | inferno-flamegraph > tracing-flamegraph.svg
