#!/bin/bash
set -eou pipefail

# if ! cargo-clippy &>/dev/null; then rustup component add clippy; fi

cargo fmt &
cargo clippy --workspace --all-features --all-targets --no-deps --exclude bindings_wasm -- -D warnings &
cargo clippy --workspace --manifest-path "./bindings_wasm/Cargo.toml" --all-features --all-targets --no-deps --exclude bindings_wasm -- -D warnings

wait
