#!/bin/bash
set -eou pipefail

files=""
while IFS= read -r file; do
    if [[ "${file}" == *".git/"* ]]; then
        continue
    fi
    if head "${file}" | grep -q "#!"; then
        files="${files} ${file}"
    fi
done < <(printf '%s\n' "$(find dev -type f)")

# shellcheck disable=SC2086 # Intended splitting of files
shellcheck -e SC1091 ${files}
