#!/usr/bin/env bash

set -eou pipefail

WORKSPACE_ROOT="$(cargo metadata --format-version 1 | jq -r .workspace_root)"
cd "${WORKSPACE_ROOT}"

export RUST_BACKTRACE="full"

cargo llvm-cov clean --profraw-only --workspace

cargo llvm-cov nextest --no-fail-fast --no-report --profile ci

mkdir -p coverage
rm -rf coverage/*

echo "Generating coverage report"
time cargo llvm-cov report --output-path coverage/lcov --lcov
echo "Generating coverage report html"
time cargo llvm-cov report --output-dir coverage/ --html
