#!/bin/bash
set -eou pipefail

# Local script to release android jniLibs with same environment as CI

if [[ "${OSTYPE}" == "darwin"* ]]; then
  if ! which nix &>/dev/null; then curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --determinate; fi
fi

nix develop . --command cargo ndk -o bindings_ffi/jniLibs/ --manifest-path ./bindings_ffi/Cargo.toml \
  -t aarch64-linux-android \
  -t x86_64-linux-android \
  -t i686-linux-android \
  -t armv7-linux-androideabi \
  -- build --release

LIBRARY_NAME="libxmtpv3"
TARGET_NAME="libuniffi_xmtpv3"

mv ./bindings_ffi/jniLibs/arm64-v8a/$LIBRARY_NAME.so ./bindings_ffi/jniLibs/arm64-v8a/$TARGET_NAME.so &&
mv ./bindings_ffi/jniLibs/armeabi-v7a/$LIBRARY_NAME.so ./bindings_ffi/jniLibs/armeabi-v7a/$TARGET_NAME.so &&
mv ./bindings_ffi/jniLibs/x86/$LIBRARY_NAME.so ./bindings_ffi/jniLibs/x86/$TARGET_NAME.so &&
mv ./bindings_ffi/jniLibs/x86_64/$LIBRARY_NAME.so ./bindings_ffi/jniLibs/x86_64/$TARGET_NAME.so
