#!/bin/bash
set -eou pipefail

# Local script to release android jniLibs with same environment as CI

WORKSPACE_MANIFEST="$(cargo locate-project --workspace --message-format=plain)"
WORKSPACE_PATH="$(dirname "$WORKSPACE_MANIFEST")"
BINDINGS_MANIFEST="$WORKSPACE_PATH/bindings/mobile/Cargo.toml"
BINDINGS_PATH="$(dirname "$BINDINGS_MANIFEST")"
# shellcheck disable=SC2034 # TARGET_DIR may be used externally or in future
TARGET_DIR="$(cargo metadata --format-version 1 --no-deps | jq -r '.target_directory')"
XMTP_SWIFT="${1:-$(realpath ../../libxmtp-swift)}"

if [[ "${OSTYPE}" == "darwin"* ]]; then
  if ! which nix &>/dev/null; then
    echo "Nix is not installed. Please review the installation script at:"
    echo "https://install.determinate.systems/nix"
    read -p "Do you want to proceed with the installation? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --determinate
    else
      echo "Nix installation aborted. Please install Nix manually or run commands in local environment to proceed."
      exit 1
    fi
  fi
fi
# Maybe set IPHONEOS_DEPLOYMENT_TARGET to 10?
cd "$BINDINGS_PATH"
nix develop ../.. --command make swift
for file in "build/swift/xmtpv3.swift" "build/swift/libxmtp-version.txt"; do
  if [ -f "$file" ]; then
    cp "$file" "$XMTP_SWIFT/Sources/LibXMTP/$(basename "$file")"
  else
    echo "Warning: $file not found"
  fi
done
