#!/bin/bash
set -eou pipefail

RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "${1:-}" ]; then
  echo -e "${RED}First argument must be package to test -- EX: \`test-wasm-interactive xmtp_mls\`${NC}"
  exit
fi

PACKAGE=$1

WASM_BINDGEN_SPLIT_LINKED_MODULES=1 \
  WASM_BINDGEN_TEST_ONLY_WEB=1 \
  NO_HEADLESS=1 \
  cargo test --target wasm32-unknown-unknown --release \
  -p $PACKAGE -- \
  --skip xmtp_mls::subscriptions \
  --skip xmtp_mls::groups::subscriptions \
  --skip xmtp_mls::storage::encrypted_store::group_message::tests::it_cannot_insert_message_without_group \
  --skip xmtp_mls::groups::tests::process_messages_abort_on_retryable_error \
  --skip  xmtp_mls::storage::encrypted_store::group::tests::test_find_groups \
  --skip xmtp_mls::storage::encrypted_store::group::tests::test_installations_last_checked_is_updated
