#!/bin/bash
set -eou pipefail

WASM_BINDGEN_SPLIT_LINKED_MODULES=1 \
  WASM_BINDGEN_TEST_ONLY_WEB=1 \
  WASM_BINDGEN_TEST_TIMEOUT=120 \
  CHROMEDRIVER="chromedriver" \
  cargo test --target wasm32-unknown-unknown --release \
  -p xmtp_mls -- xmtp_mls::subscriptions
