#!/bin/bash
set -eou pipefail

RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "${1:-}" ]; then
  echo -e "${RED}First argument must be package to test -- EX: \`test-wasm-interactive xmtp_mls\`${NC}"
  exit
fi

PACKAGE=$1

WASM_BINDGEN_SPLIT_LINKED_MODULES=1 \
  WASM_BINDGEN_TEST_ONLY_WEB=1 \
  NO_HEADLESS=1 \
  cargo test --target wasm32-unknown-unknown --release \
  -p $PACKAGE -- subscriptions::stream_conversations::test::test_stream_welcomes
