// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: device_sync/group_backup.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Definitions for backups

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Group membership state
public enum Xmtp_DeviceSync_GroupBackup_GroupMembershipStateSave: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case allowed // = 1
  case rejected // = 2
  case pending // = 3

  /// A group is marked as this state when it is restored
  /// from a backup. This is a non-functional archive state
  /// that can be reactivated when the user is re-added to
  /// the group.
  case restored // = 4
  case pendingRemove // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .allowed
    case 2: self = .rejected
    case 3: self = .pending
    case 4: self = .restored
    case 5: self = .pendingRemove
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .allowed: return 1
    case .rejected: return 2
    case .pending: return 3
    case .restored: return 4
    case .pendingRemove: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Xmtp_DeviceSync_GroupBackup_GroupMembershipStateSave] = [
    .unspecified,
    .allowed,
    .rejected,
    .pending,
    .restored,
    .pendingRemove,
  ]

}

/// Conversation type
public enum Xmtp_DeviceSync_GroupBackup_ConversationTypeSave: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case group // = 1
  case dm // = 2
  case sync // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .group
    case 2: self = .dm
    case 3: self = .sync
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .group: return 1
    case .dm: return 2
    case .sync: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Xmtp_DeviceSync_GroupBackup_ConversationTypeSave] = [
    .unspecified,
    .group,
    .dm,
    .sync,
  ]

}

/// Proto representation of a stored group
public struct Xmtp_DeviceSync_GroupBackup_GroupSave: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Data {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var createdAtNs: Int64 {
    get {return _storage._createdAtNs}
    set {_uniqueStorage()._createdAtNs = newValue}
  }

  public var membershipState: Xmtp_DeviceSync_GroupBackup_GroupMembershipStateSave {
    get {return _storage._membershipState}
    set {_uniqueStorage()._membershipState = newValue}
  }

  public var installationsLastChecked: Int64 {
    get {return _storage._installationsLastChecked}
    set {_uniqueStorage()._installationsLastChecked = newValue}
  }

  public var addedByInboxID: String {
    get {return _storage._addedByInboxID}
    set {_uniqueStorage()._addedByInboxID = newValue}
  }

  public var welcomeID: Int64 {
    get {return _storage._welcomeID ?? 0}
    set {_uniqueStorage()._welcomeID = newValue}
  }
  /// Returns true if `welcomeID` has been explicitly set.
  public var hasWelcomeID: Bool {return _storage._welcomeID != nil}
  /// Clears the value of `welcomeID`. Subsequent reads from it will return its default value.
  public mutating func clearWelcomeID() {_uniqueStorage()._welcomeID = nil}

  public var rotatedAtNs: Int64 {
    get {return _storage._rotatedAtNs}
    set {_uniqueStorage()._rotatedAtNs = newValue}
  }

  public var conversationType: Xmtp_DeviceSync_GroupBackup_ConversationTypeSave {
    get {return _storage._conversationType}
    set {_uniqueStorage()._conversationType = newValue}
  }

  public var dmID: String {
    get {return _storage._dmID ?? String()}
    set {_uniqueStorage()._dmID = newValue}
  }
  /// Returns true if `dmID` has been explicitly set.
  public var hasDmID: Bool {return _storage._dmID != nil}
  /// Clears the value of `dmID`. Subsequent reads from it will return its default value.
  public mutating func clearDmID() {_uniqueStorage()._dmID = nil}

  public var lastMessageNs: Int64 {
    get {return _storage._lastMessageNs ?? 0}
    set {_uniqueStorage()._lastMessageNs = newValue}
  }
  /// Returns true if `lastMessageNs` has been explicitly set.
  public var hasLastMessageNs: Bool {return _storage._lastMessageNs != nil}
  /// Clears the value of `lastMessageNs`. Subsequent reads from it will return its default value.
  public mutating func clearLastMessageNs() {_uniqueStorage()._lastMessageNs = nil}

  public var messageDisappearFromNs: Int64 {
    get {return _storage._messageDisappearFromNs ?? 0}
    set {_uniqueStorage()._messageDisappearFromNs = newValue}
  }
  /// Returns true if `messageDisappearFromNs` has been explicitly set.
  public var hasMessageDisappearFromNs: Bool {return _storage._messageDisappearFromNs != nil}
  /// Clears the value of `messageDisappearFromNs`. Subsequent reads from it will return its default value.
  public mutating func clearMessageDisappearFromNs() {_uniqueStorage()._messageDisappearFromNs = nil}

  public var messageDisappearInNs: Int64 {
    get {return _storage._messageDisappearInNs ?? 0}
    set {_uniqueStorage()._messageDisappearInNs = newValue}
  }
  /// Returns true if `messageDisappearInNs` has been explicitly set.
  public var hasMessageDisappearInNs: Bool {return _storage._messageDisappearInNs != nil}
  /// Clears the value of `messageDisappearInNs`. Subsequent reads from it will return its default value.
  public mutating func clearMessageDisappearInNs() {_uniqueStorage()._messageDisappearInNs = nil}

  /// metadata fields
  public var metadata: Xmtp_DeviceSync_GroupBackup_ImmutableMetadataSave {
    get {return _storage._metadata ?? Xmtp_DeviceSync_GroupBackup_ImmutableMetadataSave()}
    set {_uniqueStorage()._metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  public var hasMetadata: Bool {return _storage._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  public mutating func clearMetadata() {_uniqueStorage()._metadata = nil}

  public var mutableMetadata: Xmtp_DeviceSync_GroupBackup_MutableMetadataSave {
    get {return _storage._mutableMetadata ?? Xmtp_DeviceSync_GroupBackup_MutableMetadataSave()}
    set {_uniqueStorage()._mutableMetadata = newValue}
  }
  /// Returns true if `mutableMetadata` has been explicitly set.
  public var hasMutableMetadata: Bool {return _storage._mutableMetadata != nil}
  /// Clears the value of `mutableMetadata`. Subsequent reads from it will return its default value.
  public mutating func clearMutableMetadata() {_uniqueStorage()._mutableMetadata = nil}

  public var pausedForVersion: String {
    get {return _storage._pausedForVersion ?? String()}
    set {_uniqueStorage()._pausedForVersion = newValue}
  }
  /// Returns true if `pausedForVersion` has been explicitly set.
  public var hasPausedForVersion: Bool {return _storage._pausedForVersion != nil}
  /// Clears the value of `pausedForVersion`. Subsequent reads from it will return its default value.
  public mutating func clearPausedForVersion() {_uniqueStorage()._pausedForVersion = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// A Groups's mutable metadata
public struct Xmtp_DeviceSync_GroupBackup_MutableMetadataSave: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var attributes: Dictionary<String,String> = [:]

  public var adminList: [String] = []

  public var superAdminList: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A Group's immutable metadata
public struct Xmtp_DeviceSync_GroupBackup_ImmutableMetadataSave: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var creatorInboxID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xmtp.device_sync.group_backup"

extension Xmtp_DeviceSync_GroupBackup_GroupMembershipStateSave: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "GROUP_MEMBERSHIP_STATE_SAVE_UNSPECIFIED"),
    1: .same(proto: "GROUP_MEMBERSHIP_STATE_SAVE_ALLOWED"),
    2: .same(proto: "GROUP_MEMBERSHIP_STATE_SAVE_REJECTED"),
    3: .same(proto: "GROUP_MEMBERSHIP_STATE_SAVE_PENDING"),
    4: .same(proto: "GROUP_MEMBERSHIP_STATE_SAVE_RESTORED"),
    5: .same(proto: "GROUP_MEMBERSHIP_STATE_SAVE_PENDING_REMOVE"),
  ]
}

extension Xmtp_DeviceSync_GroupBackup_ConversationTypeSave: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CONVERSATION_TYPE_SAVE_UNSPECIFIED"),
    1: .same(proto: "CONVERSATION_TYPE_SAVE_GROUP"),
    2: .same(proto: "CONVERSATION_TYPE_SAVE_DM"),
    3: .same(proto: "CONVERSATION_TYPE_SAVE_SYNC"),
  ]
}

extension Xmtp_DeviceSync_GroupBackup_GroupSave: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GroupSave"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "created_at_ns"),
    3: .standard(proto: "membership_state"),
    4: .standard(proto: "installations_last_checked"),
    5: .standard(proto: "added_by_inbox_id"),
    6: .standard(proto: "welcome_id"),
    7: .standard(proto: "rotated_at_ns"),
    8: .standard(proto: "conversation_type"),
    9: .standard(proto: "dm_id"),
    10: .standard(proto: "last_message_ns"),
    11: .standard(proto: "message_disappear_from_ns"),
    12: .standard(proto: "message_disappear_in_ns"),
    13: .same(proto: "metadata"),
    14: .standard(proto: "mutable_metadata"),
    15: .standard(proto: "paused_for_version"),
  ]

  fileprivate class _StorageClass {
    var _id: Data = Data()
    var _createdAtNs: Int64 = 0
    var _membershipState: Xmtp_DeviceSync_GroupBackup_GroupMembershipStateSave = .unspecified
    var _installationsLastChecked: Int64 = 0
    var _addedByInboxID: String = String()
    var _welcomeID: Int64? = nil
    var _rotatedAtNs: Int64 = 0
    var _conversationType: Xmtp_DeviceSync_GroupBackup_ConversationTypeSave = .unspecified
    var _dmID: String? = nil
    var _lastMessageNs: Int64? = nil
    var _messageDisappearFromNs: Int64? = nil
    var _messageDisappearInNs: Int64? = nil
    var _metadata: Xmtp_DeviceSync_GroupBackup_ImmutableMetadataSave? = nil
    var _mutableMetadata: Xmtp_DeviceSync_GroupBackup_MutableMetadataSave? = nil
    var _pausedForVersion: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _createdAtNs = source._createdAtNs
      _membershipState = source._membershipState
      _installationsLastChecked = source._installationsLastChecked
      _addedByInboxID = source._addedByInboxID
      _welcomeID = source._welcomeID
      _rotatedAtNs = source._rotatedAtNs
      _conversationType = source._conversationType
      _dmID = source._dmID
      _lastMessageNs = source._lastMessageNs
      _messageDisappearFromNs = source._messageDisappearFromNs
      _messageDisappearInNs = source._messageDisappearInNs
      _metadata = source._metadata
      _mutableMetadata = source._mutableMetadata
      _pausedForVersion = source._pausedForVersion
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularBytesField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._createdAtNs) }()
        case 3: try { try decoder.decodeSingularEnumField(value: &_storage._membershipState) }()
        case 4: try { try decoder.decodeSingularInt64Field(value: &_storage._installationsLastChecked) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._addedByInboxID) }()
        case 6: try { try decoder.decodeSingularInt64Field(value: &_storage._welcomeID) }()
        case 7: try { try decoder.decodeSingularInt64Field(value: &_storage._rotatedAtNs) }()
        case 8: try { try decoder.decodeSingularEnumField(value: &_storage._conversationType) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._dmID) }()
        case 10: try { try decoder.decodeSingularInt64Field(value: &_storage._lastMessageNs) }()
        case 11: try { try decoder.decodeSingularInt64Field(value: &_storage._messageDisappearFromNs) }()
        case 12: try { try decoder.decodeSingularInt64Field(value: &_storage._messageDisappearInNs) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._metadata) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._mutableMetadata) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._pausedForVersion) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._id.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._id, fieldNumber: 1)
      }
      if _storage._createdAtNs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._createdAtNs, fieldNumber: 2)
      }
      if _storage._membershipState != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._membershipState, fieldNumber: 3)
      }
      if _storage._installationsLastChecked != 0 {
        try visitor.visitSingularInt64Field(value: _storage._installationsLastChecked, fieldNumber: 4)
      }
      if !_storage._addedByInboxID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._addedByInboxID, fieldNumber: 5)
      }
      try { if let v = _storage._welcomeID {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 6)
      } }()
      if _storage._rotatedAtNs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._rotatedAtNs, fieldNumber: 7)
      }
      if _storage._conversationType != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._conversationType, fieldNumber: 8)
      }
      try { if let v = _storage._dmID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._lastMessageNs {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._messageDisappearFromNs {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._messageDisappearInNs {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._metadata {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._mutableMetadata {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._pausedForVersion {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_DeviceSync_GroupBackup_GroupSave, rhs: Xmtp_DeviceSync_GroupBackup_GroupSave) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._createdAtNs != rhs_storage._createdAtNs {return false}
        if _storage._membershipState != rhs_storage._membershipState {return false}
        if _storage._installationsLastChecked != rhs_storage._installationsLastChecked {return false}
        if _storage._addedByInboxID != rhs_storage._addedByInboxID {return false}
        if _storage._welcomeID != rhs_storage._welcomeID {return false}
        if _storage._rotatedAtNs != rhs_storage._rotatedAtNs {return false}
        if _storage._conversationType != rhs_storage._conversationType {return false}
        if _storage._dmID != rhs_storage._dmID {return false}
        if _storage._lastMessageNs != rhs_storage._lastMessageNs {return false}
        if _storage._messageDisappearFromNs != rhs_storage._messageDisappearFromNs {return false}
        if _storage._messageDisappearInNs != rhs_storage._messageDisappearInNs {return false}
        if _storage._metadata != rhs_storage._metadata {return false}
        if _storage._mutableMetadata != rhs_storage._mutableMetadata {return false}
        if _storage._pausedForVersion != rhs_storage._pausedForVersion {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_DeviceSync_GroupBackup_MutableMetadataSave: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MutableMetadataSave"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "attributes"),
    2: .standard(proto: "admin_list"),
    3: .standard(proto: "super_admin_list"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.attributes) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.adminList) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.superAdminList) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.attributes.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.attributes, fieldNumber: 1)
    }
    if !self.adminList.isEmpty {
      try visitor.visitRepeatedStringField(value: self.adminList, fieldNumber: 2)
    }
    if !self.superAdminList.isEmpty {
      try visitor.visitRepeatedStringField(value: self.superAdminList, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_DeviceSync_GroupBackup_MutableMetadataSave, rhs: Xmtp_DeviceSync_GroupBackup_MutableMetadataSave) -> Bool {
    if lhs.attributes != rhs.attributes {return false}
    if lhs.adminList != rhs.adminList {return false}
    if lhs.superAdminList != rhs.superAdminList {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_DeviceSync_GroupBackup_ImmutableMetadataSave: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImmutableMetadataSave"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "creator_inbox_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.creatorInboxID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.creatorInboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.creatorInboxID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_DeviceSync_GroupBackup_ImmutableMetadataSave, rhs: Xmtp_DeviceSync_GroupBackup_ImmutableMetadataSave) -> Bool {
    if lhs.creatorInboxID != rhs.creatorInboxID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
