// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mls/message_contents/commit_log.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Defines entries on the commit log, used for fork detection and recovery
/// XIP: https://community.xmtp.org/t/xip-68-draft-automated-fork-recovery/951

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Xmtp_Mls_MessageContents_CommitResult: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case applied // = 1
  case wrongEpoch // = 2
  case undecryptable // = 3
  case invalid // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .applied
    case 2: self = .wrongEpoch
    case 3: self = .undecryptable
    case 4: self = .invalid
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .applied: return 1
    case .wrongEpoch: return 2
    case .undecryptable: return 3
    case .invalid: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Xmtp_Mls_MessageContents_CommitResult] = [
    .unspecified,
    .applied,
    .wrongEpoch,
    .undecryptable,
    .invalid,
  ]

}

/// PlaintextCommitLogEntry indicates whether a commit was successful or not,
/// when applied on top of the indicated `last_epoch_authenticator`.
public struct Xmtp_Mls_MessageContents_PlaintextCommitLogEntry: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The group_id of the group that the commit belongs to.
  public var groupID: Data = Data()

  /// The sequence ID of the commit payload being validated.
  public var commitSequenceID: UInt64 = 0

  /// The encryption state before the commit was applied.
  public var lastEpochAuthenticator: Data = Data()

  /// Indicates whether the commit was successful, or why it failed.
  public var commitResult: Xmtp_Mls_MessageContents_CommitResult = .unspecified

  /// The epoch number after the commit was applied, if successful.
  public var appliedEpochNumber: UInt64 = 0

  /// The encryption state after the commit was applied, if successful.
  public var appliedEpochAuthenticator: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Xmtp_Mls_MessageContents_CommitLogEntry: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sequenceID: UInt64 = 0

  public var serializedCommitLogEntry: Data = Data()

  public var signature: Xmtp_Identity_Associations_RecoverableEd25519Signature {
    get {return _signature ?? Xmtp_Identity_Associations_RecoverableEd25519Signature()}
    set {_signature = newValue}
  }
  /// Returns true if `signature` has been explicitly set.
  public var hasSignature: Bool {return self._signature != nil}
  /// Clears the value of `signature`. Subsequent reads from it will return its default value.
  public mutating func clearSignature() {self._signature = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _signature: Xmtp_Identity_Associations_RecoverableEd25519Signature? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xmtp.mls.message_contents"

extension Xmtp_Mls_MessageContents_CommitResult: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "COMMIT_RESULT_UNSPECIFIED"),
    1: .same(proto: "COMMIT_RESULT_APPLIED"),
    2: .same(proto: "COMMIT_RESULT_WRONG_EPOCH"),
    3: .same(proto: "COMMIT_RESULT_UNDECRYPTABLE"),
    4: .same(proto: "COMMIT_RESULT_INVALID"),
  ]
}

extension Xmtp_Mls_MessageContents_PlaintextCommitLogEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PlaintextCommitLogEntry"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "group_id"),
    2: .standard(proto: "commit_sequence_id"),
    3: .standard(proto: "last_epoch_authenticator"),
    4: .standard(proto: "commit_result"),
    5: .standard(proto: "applied_epoch_number"),
    6: .standard(proto: "applied_epoch_authenticator"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.groupID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.commitSequenceID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.lastEpochAuthenticator) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.commitResult) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.appliedEpochNumber) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.appliedEpochAuthenticator) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.groupID.isEmpty {
      try visitor.visitSingularBytesField(value: self.groupID, fieldNumber: 1)
    }
    if self.commitSequenceID != 0 {
      try visitor.visitSingularUInt64Field(value: self.commitSequenceID, fieldNumber: 2)
    }
    if !self.lastEpochAuthenticator.isEmpty {
      try visitor.visitSingularBytesField(value: self.lastEpochAuthenticator, fieldNumber: 3)
    }
    if self.commitResult != .unspecified {
      try visitor.visitSingularEnumField(value: self.commitResult, fieldNumber: 4)
    }
    if self.appliedEpochNumber != 0 {
      try visitor.visitSingularUInt64Field(value: self.appliedEpochNumber, fieldNumber: 5)
    }
    if !self.appliedEpochAuthenticator.isEmpty {
      try visitor.visitSingularBytesField(value: self.appliedEpochAuthenticator, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_PlaintextCommitLogEntry, rhs: Xmtp_Mls_MessageContents_PlaintextCommitLogEntry) -> Bool {
    if lhs.groupID != rhs.groupID {return false}
    if lhs.commitSequenceID != rhs.commitSequenceID {return false}
    if lhs.lastEpochAuthenticator != rhs.lastEpochAuthenticator {return false}
    if lhs.commitResult != rhs.commitResult {return false}
    if lhs.appliedEpochNumber != rhs.appliedEpochNumber {return false}
    if lhs.appliedEpochAuthenticator != rhs.appliedEpochAuthenticator {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_CommitLogEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommitLogEntry"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "sequence_id"),
    2: .standard(proto: "serialized_commit_log_entry"),
    3: .same(proto: "signature"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.sequenceID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.serializedCommitLogEntry) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._signature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.sequenceID != 0 {
      try visitor.visitSingularUInt64Field(value: self.sequenceID, fieldNumber: 1)
    }
    if !self.serializedCommitLogEntry.isEmpty {
      try visitor.visitSingularBytesField(value: self.serializedCommitLogEntry, fieldNumber: 2)
    }
    try { if let v = self._signature {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_CommitLogEntry, rhs: Xmtp_Mls_MessageContents_CommitLogEntry) -> Bool {
    if lhs.sequenceID != rhs.sequenceID {return false}
    if lhs.serializedCommitLogEntry != rhs.serializedCommitLogEntry {return false}
    if lhs._signature != rhs._signature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
