[bindings.swift.custom_types.Message]
lift = "Message(data: {})"
lower = "{}.data"

[bindings.swift.custom_types.Timestamp]
lift = "Timestamp(ns: {})"
lower = "{}.ns"

[bindings.kotlin]
android = true
android_cleaner = true

[bindings.kotlin.custom_types.Message]
lift = "Message({})"
lower = "{}.data"

[bindings.kotlin.custom_types.Timestamp]
lift = "Timestamp({})"
lower = "{}.ns"

[bindings.typescript.customTypes.Message]
imports = [["Message", "./runtime"]]
lift = "new Message({})"
lower = "{}.data"

[bindings.typescript.customTypes.Timestamp]
imports = [["Timestamp", "./runtime"]]
lift = "new Timestamp({})"
lower = "{}.ns"
