#!/bin/bash
set -eou pipefail

cargo llvm-cov --open --ignore-filename-regex "xmtp_proto/src/gen" nextest --no-fail-fast --profile ci --workspace --exclude xmtpv3 --exclude bindings_node --exclude bindings_wasm
