#!/bin/bash
set -eou pipefail

# Run MLS tests for D14n
# Skips tests for unimplemented features (streams)

EXTRA_FLAGS=${1:-}
cargo nextest run $EXTRA_FLAGS --features d14n --profile ci-d14n -E 'package(xmtp_mls)' -E 'rdeps(xmtp_mls)'
