#!/bin/bash
set -eou pipefail

export RUSTFLAGS="-Ctarget-feature=+bulk-memory,+mutable-globals,+atomics ${RUSTFLAGS:=}"

WASM_BINDGEN_SPLIT_LINKED_MODULES=1 \
  WASM_BINDGEN_TEST_ONLY_WEB=1 \
  WASM_BINDGEN_TEST_TIMEOUT=180 \
  CHROMEDRIVER="chromedriver" \
  cargo test --target wasm32-unknown-unknown --release \
  -p xmtp_mls -p xmtp_id -p xmtp_api_http -p xmtp_cryptography -p xmtp_api -p xmtp_api_d14n -- \
  --skip xmtp_mls::storage::encrypted_store::group_message::tests::it_cannot_insert_message_without_group \
  --skip xmtp_mls::groups::tests::process_messages_abort_on_retryable_error \
  --skip  xmtp_mls::storage::encrypted_store::group::tests::test_find_groups \
  --skip xmtp_mls::storage::encrypted_store::group::tests::test_installations_last_checked_is_updated
