#!/usr/bin/env bash
set -eou pipefail

# Setup required tools
if [[ "$(uname -s)" == "Darwin" ]]; then
  CHROMEDRIVER="$(which chromedriver 2>/dev/null || true)"
  if [[ -z "${CHROMEDRIVER}" ]]; then
    echo "Installing chromedriver"
    brew install chromedriver
  fi
fi

export WASM_BINDGEN_TEST_ONLY_WEB=1
export WASM_BINDGEN_TEST_TIMEOUT=180
export CHROMEDRIVER="chromedriver"

cargo nextest run \
  --profile ci \
  --workspace -E 'platform(target)' \
  --target wasm32-unknown-unknown --release \
  --exclude xdbg --exclude xmtpv3 --exclude bindings_node --exclude mls_validation_service --exclude xmtp_cli --exclude xmtp_api_grpc
