#!/bin/bash
set -eou pipefail

export RUSTFLAGS="-Ctarget-feature=+bulk-memory,+mutable-globals,+atomics --cfg getrandom_backend=\"wasm_js\"${RUSTFLAGS:=}"

WASM_BINDGEN_TEST_ONLY_WEB=1 \
  WASM_BINDGEN_TEST_TIMEOUT=180 \
  CHROMEDRIVER="chromedriver" \
  cargo nextest run \
  --profile ci \
  --workspace -E 'platform(target) and not test(it_cannot_insert_message_without_group)' \
  --target wasm32-unknown-unknown --release \
  --exclude xdbg --exclude xmtpv3 --exclude bindings_node --exclude mls_validation_service --exclude xmtp_cli --exclude xmtp_api_grpc
