#!/bin/bash
set -eou pipefail

RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "${1:-}" ]; then
  echo -e "${RED}First argument must be package to test -- EX: \`test-wasm-interactive xmtp_mls\`${NC}"
  exit
fi

PACKAGE=$1
TESTS=${2:-}

export RUSTFLAGS="-Ctarget-feature=+bulk-memory,+mutable-globals --cfg getrandom_backend=\"wasm_js\"${RUSTFLAGS:=}"
export WASM_BINDGEN_TEST_ONLY_WEB=1
# export SPLIT_LINKED_MODULES=1
export NO_HEADLESS=1

cargo test --target wasm32-unknown-unknown --release \
  -p $PACKAGE -- \
  --skip xmtp_mls::storage::encrypted_store::group_message::tests::it_cannot_insert_message_without_group
