#!/usr/bin/env bash

set -euo

swift package plugin --allow-writing-to-package-directory swiftlint . "$@"
swift package plugin --allow-writing-to-package-directory swiftlint --config Tests/.swiftlint.yml ./Tests "$@"
