#!/bin/bash
set -eou pipefail
ROOT="$(git rev-parse --show-toplevel)"

if [[ -z "${IN_NIX_SHELL:-}" ]]; then
    exec nix develop "${ROOT}#ios" --command "$0" "$@"
fi

cd "${ROOT}/sdks/ios"
swiftlint lint .
swiftlint lint --config Tests/.swiftlint.yml ./Tests
