#!/bin/bash
set -eou pipefail

cargo clippy --quiet --locked --workspace --all-features --all-targets --no-deps --exclude bindings_wasm -- -Dwarnings &
pid1=$!
cargo clippy --quiet --locked --manifest-path "./bindings/wasm/Cargo.toml" --all-features --target wasm32-unknown-unknown --no-deps -- -Dwarnings &
pid2=$!
cargo check --quiet --locked --tests --target wasm32-unknown-unknown -p bindings_wasm &
pid3=$!

if wait $pid1 && wait $pid2 && wait $pid3; then
  echo "Lints Good ✅"
else
  echo "Lints Bad ❌"
  exit 1
fi
