#!/bin/bash
set -eou pipefail

WORKSPACE_MANIFEST="$(cargo locate-project --workspace --message-format=plain)"
WORKSPACE_PATH="$(dirname $WORKSPACE_MANIFEST)"

$WORKSPACE_PATH/dev/ci/format

$WORKSPACE_PATH/dev/ci/lint

$WORKSPACE_PATH/dev/ci/test

wait

echo "All Good ✅"
