#!/bin/bash
set -eou pipefail

WORKSPACE_MANIFEST="$(cargo locate-project --workspace --message-format=plain)"
WORKSPACE_PATH="$(dirname $WORKSPACE_MANIFEST)"

RUST_LOG=off \
WASM_BINDGEN_SPLIT_LINKED_MODULES=1 \
WASM_BINDGEN_TEST_ONLY_WEB=1 \
WASM_BINDGEN_TEST_TIMEOUT=180 \
RSTEST_TIMEOUT=60 \
cargo test --quiet --locked --release --target wasm32-unknown-unknown \
  -p xmtp_mls -p xmtp_cryptography -p xmtp_common \
  -p xmtp_api -p xmtp_id -p xmtp_db -p xmtp_api_d14n \
  --\
  --skip encrypted_store::group_message::tests::it_cannot_insert_message_without_group
$WORKSPACE_PATH/dev/test/v3 "--profile ci"

echo "Tests Good ✅"

