#!/bin/bash
set -eou pipefail

export RUSTFLAGS="-Ctarget-feature=+bulk-memory,+mutable-globals,+atomics --cfg getrandom_backend=\"wasm_js\"${RUSTFLAGS:=}"

WASM_BINDGEN_TEST_ONLY_WEB=1 \
  WASM_BINDGEN_TEST_TIMEOUT=180 \
  CHROMEDRIVER="chromedriver" \
  cargo nextest run \
  --workspace -E 'platform(target)' \
  --target wasm32-unknown-unknown --release \
  --exclude xdbg xmtpv3 bindings_node mls_validation_service xmtp_cli xmtp_api_grpc \
  --skip xmtp_mls::storage::encrypted_store::group_message::tests::it_cannot_insert_message_without_group
