#!/bin/bash
set -eou pipefail

export RUSTFLAGS="-Ctarget-feature=+bulk-memory,+mutable-globals,+atomics --cfg getrandom_backend=\"wasm_js\" ${RUSTFLAGS:=}"
CARGO="nix develop .#ci --command cargo"

# Nixpkgs does not yet have emscripten 4 packaged, which sqlite-wasm requires
# https://github.com/NixOS/nixpkgs/pull/380263
if [ ! -d "emsdk" ] >/dev/null 2>&1; then
  echo "installing emscripten"
  git clone https://github.com/emscripten-core/emsdk.git
  ./emsdk/emsdk install latest
  ./emsdk/emsdk activate latest
  source ./emsdk/emsdk_env.sh
else
  source ./emsdk/emsdk_env.sh
fi

WASM_BINDGEN_TEST_ONLY_WEB=1 \
  WASM_BINDGEN_TEST_TIMEOUT=180 \
  CHROMEDRIVER="chromedriver" \
  $CARGO nextest run \
  --workspace -E 'platform(target) and not test(it_cannot_insert_message_without_group)' \
  --target wasm32-unknown-unknown --release \
  --exclude xdbg --exclude xmtpv3 --exclude bindings_node --exclude mls_validation_service --exclude xmtp_cli --exclude xmtp_api_grpc
