pluginManagement {
    def pins = new Properties()
    file('../../sdks/android/gradle/toolchain.properties').withInputStream { pins.load(it) }
    resolutionStrategy.eachPlugin {
        def version = pins.getProperty("plugin.${requested.id.id}")
        if (version) useVersion(version)
    }
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "xmtp-messenger"
include ':example'
include ':example-shared'
project(':example').projectDir = file('app')
project(':example-shared').projectDir = file('shared')
includeBuild('../../sdks/android') {
    dependencySubstitution {
        substitute module('org.xmtp:android') using project(':library')
    }
}
