// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mls/message_contents/group_metadata.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Group immutable metadata

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Defines the type of conversation
public enum Xmtp_Mls_MessageContents_ConversationType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case group // = 1
  case dm // = 2
  case sync // = 3
  case oneshot // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .group
    case 2: self = .dm
    case 3: self = .sync
    case 4: self = .oneshot
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .group: return 1
    case .dm: return 2
    case .sync: return 3
    case .oneshot: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Xmtp_Mls_MessageContents_ConversationType] = [
    .unspecified,
    .group,
    .dm,
    .sync,
    .oneshot,
  ]

}

/// Parent message for group metadata
public struct Xmtp_Mls_MessageContents_GroupMetadataV1: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var conversationType: Xmtp_Mls_MessageContents_ConversationType = .unspecified

  /// This will be removed soon
  public var creatorAccountAddress: String = String()

  public var creatorInboxID: String = String()

  /// Should only be present for CONVERSATION_TYPE_DM
  public var dmMembers: Xmtp_Mls_MessageContents_DmMembers {
    get {return _dmMembers ?? Xmtp_Mls_MessageContents_DmMembers()}
    set {_dmMembers = newValue}
  }
  /// Returns true if `dmMembers` has been explicitly set.
  public var hasDmMembers: Bool {return self._dmMembers != nil}
  /// Clears the value of `dmMembers`. Subsequent reads from it will return its default value.
  public mutating func clearDmMembers() {self._dmMembers = nil}

  /// Should only be present for CONVERSATION_TYPE_ONESHOT
  public var oneshotMessage: Xmtp_Mls_MessageContents_OneshotMessage {
    get {return _oneshotMessage ?? Xmtp_Mls_MessageContents_OneshotMessage()}
    set {_oneshotMessage = newValue}
  }
  /// Returns true if `oneshotMessage` has been explicitly set.
  public var hasOneshotMessage: Bool {return self._oneshotMessage != nil}
  /// Clears the value of `oneshotMessage`. Subsequent reads from it will return its default value.
  public mutating func clearOneshotMessage() {self._oneshotMessage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _dmMembers: Xmtp_Mls_MessageContents_DmMembers? = nil
  fileprivate var _oneshotMessage: Xmtp_Mls_MessageContents_OneshotMessage? = nil
}

/// Wrapper around an Inbox Id
public struct Xmtp_Mls_MessageContents_Inbox: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inboxID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Ordering does not matter here
public struct Xmtp_Mls_MessageContents_DmMembers: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var dmMemberOne: Xmtp_Mls_MessageContents_Inbox {
    get {return _dmMemberOne ?? Xmtp_Mls_MessageContents_Inbox()}
    set {_dmMemberOne = newValue}
  }
  /// Returns true if `dmMemberOne` has been explicitly set.
  public var hasDmMemberOne: Bool {return self._dmMemberOne != nil}
  /// Clears the value of `dmMemberOne`. Subsequent reads from it will return its default value.
  public mutating func clearDmMemberOne() {self._dmMemberOne = nil}

  public var dmMemberTwo: Xmtp_Mls_MessageContents_Inbox {
    get {return _dmMemberTwo ?? Xmtp_Mls_MessageContents_Inbox()}
    set {_dmMemberTwo = newValue}
  }
  /// Returns true if `dmMemberTwo` has been explicitly set.
  public var hasDmMemberTwo: Bool {return self._dmMemberTwo != nil}
  /// Clears the value of `dmMemberTwo`. Subsequent reads from it will return its default value.
  public mutating func clearDmMemberTwo() {self._dmMemberTwo = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _dmMemberOne: Xmtp_Mls_MessageContents_Inbox? = nil
  fileprivate var _dmMemberTwo: Xmtp_Mls_MessageContents_Inbox? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xmtp.mls.message_contents"

extension Xmtp_Mls_MessageContents_ConversationType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CONVERSATION_TYPE_UNSPECIFIED\0\u{1}CONVERSATION_TYPE_GROUP\0\u{1}CONVERSATION_TYPE_DM\0\u{1}CONVERSATION_TYPE_SYNC\0\u{1}CONVERSATION_TYPE_ONESHOT\0")
}

extension Xmtp_Mls_MessageContents_GroupMetadataV1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GroupMetadataV1"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}conversation_type\0\u{3}creator_account_address\0\u{3}creator_inbox_id\0\u{3}dm_members\0\u{3}oneshot_message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.conversationType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.creatorAccountAddress) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.creatorInboxID) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._dmMembers) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._oneshotMessage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.conversationType != .unspecified {
      try visitor.visitSingularEnumField(value: self.conversationType, fieldNumber: 1)
    }
    if !self.creatorAccountAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.creatorAccountAddress, fieldNumber: 2)
    }
    if !self.creatorInboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.creatorInboxID, fieldNumber: 3)
    }
    try { if let v = self._dmMembers {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._oneshotMessage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_GroupMetadataV1, rhs: Xmtp_Mls_MessageContents_GroupMetadataV1) -> Bool {
    if lhs.conversationType != rhs.conversationType {return false}
    if lhs.creatorAccountAddress != rhs.creatorAccountAddress {return false}
    if lhs.creatorInboxID != rhs.creatorInboxID {return false}
    if lhs._dmMembers != rhs._dmMembers {return false}
    if lhs._oneshotMessage != rhs._oneshotMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_Inbox: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Inbox"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}inbox_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.inboxID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.inboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.inboxID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_Inbox, rhs: Xmtp_Mls_MessageContents_Inbox) -> Bool {
    if lhs.inboxID != rhs.inboxID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_DmMembers: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DmMembers"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}dm_member_one\0\u{3}dm_member_two\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._dmMemberOne) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._dmMemberTwo) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._dmMemberOne {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._dmMemberTwo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_DmMembers, rhs: Xmtp_Mls_MessageContents_DmMembers) -> Bool {
    if lhs._dmMemberOne != rhs._dmMemberOne {return false}
    if lhs._dmMemberTwo != rhs._dmMemberTwo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
