apiVersion: 1
datasources:
  - name: Fly Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: https://api.fly.io/prometheus/xmtp-labs
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: $FLY_METRICS_AUTHORIZATION
  - name: Trace metrics
    uid: trace-metrics
    type: prometheus
    access: proxy
    url: http://xmtp-backend-dev-prometheus.internal:9090
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://xmtp-backend-dev-tempo.internal:3200
    jsonData:
      serviceMap:
        datasourceUid: trace-metrics
      nodeGraph:
        enabled: true
