CREATE TABLE identity_updates (
    -- The inbox_id the update refers to
    "inbox_id" TEXT NOT NULL,
    -- The sequence_id of the update
    "sequence_id" BIGINT NOT NULL,
    -- Based on the timestamp given by the server
    "server_timestamp_ns" BIGINT NOT NULL,
    -- Random ID generated by group creator
    "payload" BLOB NOT NULL,
    -- Compound primary key of the `inbox_id` and `sequence_id`
    PRIMARY KEY ("inbox_id", "sequence_id")
);

CREATE INDEX idx_identity_updates_inbox_id_sequence_id_asc ON identity_updates (inbox_id, sequence_id ASC);