experimental-features = nix-command flakes
accept-flake-config = true
extra-substituters = https://xmtp.cachix.org
extra-trusted-public-keys = xmtp.cachix.org-1:nFPFrqLQ9kjYQKiWL7gKq6llcNEeaV4iI+Ka1F+Tmq0=
