[package]
name = "xmtp-sdk-bindgen"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
heck = "0.5"
tempfile = "3.27"
toml.workspace = true
ubrn_bindgen.workspace = true
ubrn_common.workspace = true
uniffi_bindgen.workspace = true
uniffi_meta.workspace = true

[dev-dependencies]
xmtp_common = { workspace = true, features = ["test-utils"] }
