// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mls/message_contents/content_types/multi_remote_attachment.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// multi_remote_attachment.proto
/// This file defines the MultiRemoteAttachment message type and is associated with the following ContentTypeId:
///
/// ContentTypeId {
///     authority_id: "xmtp.org",
///     type_id:      "multiRemoteStaticContent",
///     version_major: 1,
///     version_minor: 0,
/// }

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// MultiRemoteAttachment message type
public struct Xmtp_Mls_MessageContents_ContentTypes_MultiRemoteAttachment: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Array of attachment information
  public var attachments: [Xmtp_Mls_MessageContents_ContentTypes_RemoteAttachmentInfo] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Xmtp_Mls_MessageContents_ContentTypes_RemoteAttachmentInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The SHA256 hash of the remote content
  public var contentDigest: String = String()

  /// A 32 byte array for decrypting the remote content payload
  public var secret: Data = Data()

  /// A byte array for the nonce used to encrypt the remote content payload
  public var nonce: Data = Data()

  /// A byte array for the salt used to encrypt the remote content payload
  public var salt: Data = Data()

  /// The scheme of the URL. Must be "https://"
  public var scheme: String = String()

  /// The URL of the remote content
  public var url: String = String()

  /// The size of the encrypted content in bytes (max size of 4GB)
  public var contentLength: UInt32 {
    get {return _contentLength ?? 0}
    set {_contentLength = newValue}
  }
  /// Returns true if `contentLength` has been explicitly set.
  public var hasContentLength: Bool {return self._contentLength != nil}
  /// Clears the value of `contentLength`. Subsequent reads from it will return its default value.
  public mutating func clearContentLength() {self._contentLength = nil}

  /// The filename of the remote content
  public var filename: String {
    get {return _filename ?? String()}
    set {_filename = newValue}
  }
  /// Returns true if `filename` has been explicitly set.
  public var hasFilename: Bool {return self._filename != nil}
  /// Clears the value of `filename`. Subsequent reads from it will return its default value.
  public mutating func clearFilename() {self._filename = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _contentLength: UInt32? = nil
  fileprivate var _filename: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xmtp.mls.message_contents.content_types"

extension Xmtp_Mls_MessageContents_ContentTypes_MultiRemoteAttachment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MultiRemoteAttachment"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}attachments\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.attachments) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.attachments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.attachments, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_ContentTypes_MultiRemoteAttachment, rhs: Xmtp_Mls_MessageContents_ContentTypes_MultiRemoteAttachment) -> Bool {
    if lhs.attachments != rhs.attachments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Xmtp_Mls_MessageContents_ContentTypes_RemoteAttachmentInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RemoteAttachmentInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}content_digest\0\u{1}secret\0\u{1}nonce\0\u{1}salt\0\u{1}scheme\0\u{1}url\0\u{3}content_length\0\u{1}filename\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.contentDigest) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.secret) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.nonce) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.salt) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.scheme) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self._contentLength) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._filename) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.contentDigest.isEmpty {
      try visitor.visitSingularStringField(value: self.contentDigest, fieldNumber: 1)
    }
    if !self.secret.isEmpty {
      try visitor.visitSingularBytesField(value: self.secret, fieldNumber: 2)
    }
    if !self.nonce.isEmpty {
      try visitor.visitSingularBytesField(value: self.nonce, fieldNumber: 3)
    }
    if !self.salt.isEmpty {
      try visitor.visitSingularBytesField(value: self.salt, fieldNumber: 4)
    }
    if !self.scheme.isEmpty {
      try visitor.visitSingularStringField(value: self.scheme, fieldNumber: 5)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 6)
    }
    try { if let v = self._contentLength {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._filename {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Xmtp_Mls_MessageContents_ContentTypes_RemoteAttachmentInfo, rhs: Xmtp_Mls_MessageContents_ContentTypes_RemoteAttachmentInfo) -> Bool {
    if lhs.contentDigest != rhs.contentDigest {return false}
    if lhs.secret != rhs.secret {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.salt != rhs.salt {return false}
    if lhs.scheme != rhs.scheme {return false}
    if lhs.url != rhs.url {return false}
    if lhs._contentLength != rhs._contentLength {return false}
    if lhs._filename != rhs._filename {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
