# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationService
#  pod "web3.swift"
#  pod 'KeychainAccess'
end

target 'XMTPiOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XMTPiOSExample
#  pod 'WalletConnectSwift'
#  pod "web3.swift"
#  pod 'KeychainAccess'
#  pod "XMTP", path: '../'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
       end
    end
  end
end
