// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `message_contents/public_key.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

///  UnsignedPublicKey represents a generalized public key,
///  defined as a union to support cryptographic algorithm agility.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:xmtp.message_contents.UnsignedPublicKey)
pub struct UnsignedPublicKey {
    // message fields
    // @@protoc_insertion_point(field:xmtp.message_contents.UnsignedPublicKey.created_ns)
    pub created_ns: u64,
    // message oneof groups
    pub union: ::std::option::Option<unsigned_public_key::Union>,
    // special fields
    // @@protoc_insertion_point(special_field:xmtp.message_contents.UnsignedPublicKey.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UnsignedPublicKey {
    fn default() -> &'a UnsignedPublicKey {
        <UnsignedPublicKey as ::protobuf::Message>::default_instance()
    }
}

impl UnsignedPublicKey {
    pub fn new() -> UnsignedPublicKey {
        ::std::default::Default::default()
    }

    // .xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed secp256k1_uncompressed = 3;

    pub fn secp256k1_uncompressed(&self) -> &unsigned_public_key::Secp256k1Uncompressed {
        match self.union {
            ::std::option::Option::Some(unsigned_public_key::Union::Secp256k1Uncompressed(ref v)) => v,
            _ => <unsigned_public_key::Secp256k1Uncompressed as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_secp256k1_uncompressed(&mut self) {
        self.union = ::std::option::Option::None;
    }

    pub fn has_secp256k1_uncompressed(&self) -> bool {
        match self.union {
            ::std::option::Option::Some(unsigned_public_key::Union::Secp256k1Uncompressed(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_secp256k1_uncompressed(&mut self, v: unsigned_public_key::Secp256k1Uncompressed) {
        self.union = ::std::option::Option::Some(unsigned_public_key::Union::Secp256k1Uncompressed(v))
    }

    // Mutable pointer to the field.
    pub fn mut_secp256k1_uncompressed(&mut self) -> &mut unsigned_public_key::Secp256k1Uncompressed {
        if let ::std::option::Option::Some(unsigned_public_key::Union::Secp256k1Uncompressed(_)) = self.union {
        } else {
            self.union = ::std::option::Option::Some(unsigned_public_key::Union::Secp256k1Uncompressed(unsigned_public_key::Secp256k1Uncompressed::new()));
        }
        match self.union {
            ::std::option::Option::Some(unsigned_public_key::Union::Secp256k1Uncompressed(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_secp256k1_uncompressed(&mut self) -> unsigned_public_key::Secp256k1Uncompressed {
        if self.has_secp256k1_uncompressed() {
            match self.union.take() {
                ::std::option::Option::Some(unsigned_public_key::Union::Secp256k1Uncompressed(v)) => v,
                _ => panic!(),
            }
        } else {
            unsigned_public_key::Secp256k1Uncompressed::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "created_ns",
            |m: &UnsignedPublicKey| { &m.created_ns },
            |m: &mut UnsignedPublicKey| { &mut m.created_ns },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, unsigned_public_key::Secp256k1Uncompressed>(
            "secp256k1_uncompressed",
            UnsignedPublicKey::has_secp256k1_uncompressed,
            UnsignedPublicKey::secp256k1_uncompressed,
            UnsignedPublicKey::mut_secp256k1_uncompressed,
            UnsignedPublicKey::set_secp256k1_uncompressed,
        ));
        oneofs.push(unsigned_public_key::Union::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UnsignedPublicKey>(
            "UnsignedPublicKey",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UnsignedPublicKey {
    const NAME: &'static str = "UnsignedPublicKey";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.created_ns = is.read_uint64()?;
                },
                26 => {
                    self.union = ::std::option::Option::Some(unsigned_public_key::Union::Secp256k1Uncompressed(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.created_ns != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.created_ns);
        }
        if let ::std::option::Option::Some(ref v) = self.union {
            match v {
                &unsigned_public_key::Union::Secp256k1Uncompressed(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.created_ns != 0 {
            os.write_uint64(1, self.created_ns)?;
        }
        if let ::std::option::Option::Some(ref v) = self.union {
            match v {
                &unsigned_public_key::Union::Secp256k1Uncompressed(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UnsignedPublicKey {
        UnsignedPublicKey::new()
    }

    fn clear(&mut self) {
        self.created_ns = 0;
        self.union = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UnsignedPublicKey {
        static instance: UnsignedPublicKey = UnsignedPublicKey {
            created_ns: 0,
            union: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UnsignedPublicKey {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UnsignedPublicKey").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UnsignedPublicKey {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UnsignedPublicKey {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `UnsignedPublicKey`
pub mod unsigned_public_key {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:xmtp.message_contents.UnsignedPublicKey.union)
    pub enum Union {
        // @@protoc_insertion_point(oneof_field:xmtp.message_contents.UnsignedPublicKey.secp256k1_uncompressed)
        Secp256k1Uncompressed(Secp256k1Uncompressed),
    }

    impl ::protobuf::Oneof for Union {
    }

    impl ::protobuf::OneofFull for Union {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::UnsignedPublicKey as ::protobuf::MessageFull>::descriptor().oneof_by_name("union").unwrap()).clone()
        }
    }

    impl Union {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Union>("union")
        }
    }
    ///  EC: SECP256k1
    #[derive(PartialEq,Clone,Default,Debug)]
    // @@protoc_insertion_point(message:xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed)
    pub struct Secp256k1Uncompressed {
        // message fields
        ///  uncompressed point with prefix (0x04) [ P || X || Y ], 65 bytes
        // @@protoc_insertion_point(field:xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed.bytes)
        pub bytes: ::std::vec::Vec<u8>,
        // special fields
        // @@protoc_insertion_point(special_field:xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Secp256k1Uncompressed {
        fn default() -> &'a Secp256k1Uncompressed {
            <Secp256k1Uncompressed as ::protobuf::Message>::default_instance()
        }
    }

    impl Secp256k1Uncompressed {
        pub fn new() -> Secp256k1Uncompressed {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(1);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "bytes",
                |m: &Secp256k1Uncompressed| { &m.bytes },
                |m: &mut Secp256k1Uncompressed| { &mut m.bytes },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Secp256k1Uncompressed>(
                "UnsignedPublicKey.Secp256k1Uncompressed",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for Secp256k1Uncompressed {
        const NAME: &'static str = "Secp256k1Uncompressed";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.bytes = is.read_bytes()?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.bytes.is_empty() {
                my_size += ::protobuf::rt::bytes_size(1, &self.bytes);
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.bytes.is_empty() {
                os.write_bytes(1, &self.bytes)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Secp256k1Uncompressed {
            Secp256k1Uncompressed::new()
        }

        fn clear(&mut self) {
            self.bytes.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Secp256k1Uncompressed {
            static instance: Secp256k1Uncompressed = Secp256k1Uncompressed {
                bytes: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for Secp256k1Uncompressed {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("UnsignedPublicKey.Secp256k1Uncompressed").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for Secp256k1Uncompressed {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for Secp256k1Uncompressed {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

///  SignedPublicKey 
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:xmtp.message_contents.SignedPublicKey)
pub struct SignedPublicKey {
    // message fields
    // @@protoc_insertion_point(field:xmtp.message_contents.SignedPublicKey.key_bytes)
    pub key_bytes: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:xmtp.message_contents.SignedPublicKey.signature)
    pub signature: ::protobuf::MessageField<super::signature::Signature>,
    // special fields
    // @@protoc_insertion_point(special_field:xmtp.message_contents.SignedPublicKey.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SignedPublicKey {
    fn default() -> &'a SignedPublicKey {
        <SignedPublicKey as ::protobuf::Message>::default_instance()
    }
}

impl SignedPublicKey {
    pub fn new() -> SignedPublicKey {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "key_bytes",
            |m: &SignedPublicKey| { &m.key_bytes },
            |m: &mut SignedPublicKey| { &mut m.key_bytes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::signature::Signature>(
            "signature",
            |m: &SignedPublicKey| { &m.signature },
            |m: &mut SignedPublicKey| { &mut m.signature },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SignedPublicKey>(
            "SignedPublicKey",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SignedPublicKey {
    const NAME: &'static str = "SignedPublicKey";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.key_bytes = is.read_bytes()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.signature)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.key_bytes.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.key_bytes);
        }
        if let Some(v) = self.signature.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.key_bytes.is_empty() {
            os.write_bytes(1, &self.key_bytes)?;
        }
        if let Some(v) = self.signature.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SignedPublicKey {
        SignedPublicKey::new()
    }

    fn clear(&mut self) {
        self.key_bytes.clear();
        self.signature.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SignedPublicKey {
        static instance: SignedPublicKey = SignedPublicKey {
            key_bytes: ::std::vec::Vec::new(),
            signature: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SignedPublicKey {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SignedPublicKey").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SignedPublicKey {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SignedPublicKey {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  PublicKeyBundle packages the cryptographic keys associated with a wallet.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:xmtp.message_contents.SignedPublicKeyBundle)
pub struct SignedPublicKeyBundle {
    // message fields
    ///  Identity key MUST be signed by the wallet.
    // @@protoc_insertion_point(field:xmtp.message_contents.SignedPublicKeyBundle.identity_key)
    pub identity_key: ::protobuf::MessageField<SignedPublicKey>,
    ///  Pre-key MUST be signed by the identity key.
    // @@protoc_insertion_point(field:xmtp.message_contents.SignedPublicKeyBundle.pre_key)
    pub pre_key: ::protobuf::MessageField<SignedPublicKey>,
    // special fields
    // @@protoc_insertion_point(special_field:xmtp.message_contents.SignedPublicKeyBundle.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SignedPublicKeyBundle {
    fn default() -> &'a SignedPublicKeyBundle {
        <SignedPublicKeyBundle as ::protobuf::Message>::default_instance()
    }
}

impl SignedPublicKeyBundle {
    pub fn new() -> SignedPublicKeyBundle {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, SignedPublicKey>(
            "identity_key",
            |m: &SignedPublicKeyBundle| { &m.identity_key },
            |m: &mut SignedPublicKeyBundle| { &mut m.identity_key },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, SignedPublicKey>(
            "pre_key",
            |m: &SignedPublicKeyBundle| { &m.pre_key },
            |m: &mut SignedPublicKeyBundle| { &mut m.pre_key },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SignedPublicKeyBundle>(
            "SignedPublicKeyBundle",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SignedPublicKeyBundle {
    const NAME: &'static str = "SignedPublicKeyBundle";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.identity_key)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pre_key)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.identity_key.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.pre_key.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.identity_key.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.pre_key.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SignedPublicKeyBundle {
        SignedPublicKeyBundle::new()
    }

    fn clear(&mut self) {
        self.identity_key.clear();
        self.pre_key.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SignedPublicKeyBundle {
        static instance: SignedPublicKeyBundle = SignedPublicKeyBundle {
            identity_key: ::protobuf::MessageField::none(),
            pre_key: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SignedPublicKeyBundle {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SignedPublicKeyBundle").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SignedPublicKeyBundle {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SignedPublicKeyBundle {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  PublicKey represents a generalized public key,
///  defined as a union to support cryptographic algorithm agility.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:xmtp.message_contents.PublicKey)
pub struct PublicKey {
    // message fields
    // @@protoc_insertion_point(field:xmtp.message_contents.PublicKey.timestamp)
    pub timestamp: u64,
    // @@protoc_insertion_point(field:xmtp.message_contents.PublicKey.signature)
    pub signature: ::protobuf::MessageField<super::signature::Signature>,
    // message oneof groups
    pub union: ::std::option::Option<public_key::Union>,
    // special fields
    // @@protoc_insertion_point(special_field:xmtp.message_contents.PublicKey.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PublicKey {
    fn default() -> &'a PublicKey {
        <PublicKey as ::protobuf::Message>::default_instance()
    }
}

impl PublicKey {
    pub fn new() -> PublicKey {
        ::std::default::Default::default()
    }

    // .xmtp.message_contents.PublicKey.Secp256k1Uncompressed secp256k1_uncompressed = 3;

    pub fn secp256k1_uncompressed(&self) -> &public_key::Secp256k1Uncompressed {
        match self.union {
            ::std::option::Option::Some(public_key::Union::Secp256k1Uncompressed(ref v)) => v,
            _ => <public_key::Secp256k1Uncompressed as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_secp256k1_uncompressed(&mut self) {
        self.union = ::std::option::Option::None;
    }

    pub fn has_secp256k1_uncompressed(&self) -> bool {
        match self.union {
            ::std::option::Option::Some(public_key::Union::Secp256k1Uncompressed(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_secp256k1_uncompressed(&mut self, v: public_key::Secp256k1Uncompressed) {
        self.union = ::std::option::Option::Some(public_key::Union::Secp256k1Uncompressed(v))
    }

    // Mutable pointer to the field.
    pub fn mut_secp256k1_uncompressed(&mut self) -> &mut public_key::Secp256k1Uncompressed {
        if let ::std::option::Option::Some(public_key::Union::Secp256k1Uncompressed(_)) = self.union {
        } else {
            self.union = ::std::option::Option::Some(public_key::Union::Secp256k1Uncompressed(public_key::Secp256k1Uncompressed::new()));
        }
        match self.union {
            ::std::option::Option::Some(public_key::Union::Secp256k1Uncompressed(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_secp256k1_uncompressed(&mut self) -> public_key::Secp256k1Uncompressed {
        if self.has_secp256k1_uncompressed() {
            match self.union.take() {
                ::std::option::Option::Some(public_key::Union::Secp256k1Uncompressed(v)) => v,
                _ => panic!(),
            }
        } else {
            public_key::Secp256k1Uncompressed::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "timestamp",
            |m: &PublicKey| { &m.timestamp },
            |m: &mut PublicKey| { &mut m.timestamp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::signature::Signature>(
            "signature",
            |m: &PublicKey| { &m.signature },
            |m: &mut PublicKey| { &mut m.signature },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, public_key::Secp256k1Uncompressed>(
            "secp256k1_uncompressed",
            PublicKey::has_secp256k1_uncompressed,
            PublicKey::secp256k1_uncompressed,
            PublicKey::mut_secp256k1_uncompressed,
            PublicKey::set_secp256k1_uncompressed,
        ));
        oneofs.push(public_key::Union::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PublicKey>(
            "PublicKey",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PublicKey {
    const NAME: &'static str = "PublicKey";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.timestamp = is.read_uint64()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.signature)?;
                },
                26 => {
                    self.union = ::std::option::Option::Some(public_key::Union::Secp256k1Uncompressed(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.timestamp != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.timestamp);
        }
        if let Some(v) = self.signature.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let ::std::option::Option::Some(ref v) = self.union {
            match v {
                &public_key::Union::Secp256k1Uncompressed(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.timestamp != 0 {
            os.write_uint64(1, self.timestamp)?;
        }
        if let Some(v) = self.signature.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let ::std::option::Option::Some(ref v) = self.union {
            match v {
                &public_key::Union::Secp256k1Uncompressed(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PublicKey {
        PublicKey::new()
    }

    fn clear(&mut self) {
        self.timestamp = 0;
        self.signature.clear();
        self.union = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PublicKey {
        static instance: PublicKey = PublicKey {
            timestamp: 0,
            signature: ::protobuf::MessageField::none(),
            union: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PublicKey {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PublicKey").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PublicKey {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PublicKey {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `PublicKey`
pub mod public_key {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:xmtp.message_contents.PublicKey.union)
    pub enum Union {
        // @@protoc_insertion_point(oneof_field:xmtp.message_contents.PublicKey.secp256k1_uncompressed)
        Secp256k1Uncompressed(Secp256k1Uncompressed),
    }

    impl ::protobuf::Oneof for Union {
    }

    impl ::protobuf::OneofFull for Union {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::PublicKey as ::protobuf::MessageFull>::descriptor().oneof_by_name("union").unwrap()).clone()
        }
    }

    impl Union {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Union>("union")
        }
    }
    ///  The key bytes
    #[derive(PartialEq,Clone,Default,Debug)]
    // @@protoc_insertion_point(message:xmtp.message_contents.PublicKey.Secp256k1Uncompressed)
    pub struct Secp256k1Uncompressed {
        // message fields
        ///  uncompressed point with prefix (0x04) [ P || X || Y ], 65 bytes
        // @@protoc_insertion_point(field:xmtp.message_contents.PublicKey.Secp256k1Uncompressed.bytes)
        pub bytes: ::std::vec::Vec<u8>,
        // special fields
        // @@protoc_insertion_point(special_field:xmtp.message_contents.PublicKey.Secp256k1Uncompressed.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Secp256k1Uncompressed {
        fn default() -> &'a Secp256k1Uncompressed {
            <Secp256k1Uncompressed as ::protobuf::Message>::default_instance()
        }
    }

    impl Secp256k1Uncompressed {
        pub fn new() -> Secp256k1Uncompressed {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(1);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "bytes",
                |m: &Secp256k1Uncompressed| { &m.bytes },
                |m: &mut Secp256k1Uncompressed| { &mut m.bytes },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Secp256k1Uncompressed>(
                "PublicKey.Secp256k1Uncompressed",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for Secp256k1Uncompressed {
        const NAME: &'static str = "Secp256k1Uncompressed";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.bytes = is.read_bytes()?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.bytes.is_empty() {
                my_size += ::protobuf::rt::bytes_size(1, &self.bytes);
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.bytes.is_empty() {
                os.write_bytes(1, &self.bytes)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Secp256k1Uncompressed {
            Secp256k1Uncompressed::new()
        }

        fn clear(&mut self) {
            self.bytes.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Secp256k1Uncompressed {
            static instance: Secp256k1Uncompressed = Secp256k1Uncompressed {
                bytes: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for Secp256k1Uncompressed {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("PublicKey.Secp256k1Uncompressed").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for Secp256k1Uncompressed {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for Secp256k1Uncompressed {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

///  PublicKeyBundle packages the cryptographic keys associated with a wallet,
///  both senders and recipients are identified by their key bundles.
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:xmtp.message_contents.PublicKeyBundle)
pub struct PublicKeyBundle {
    // message fields
    ///  Identity key MUST be signed by the wallet.
    // @@protoc_insertion_point(field:xmtp.message_contents.PublicKeyBundle.identity_key)
    pub identity_key: ::protobuf::MessageField<PublicKey>,
    ///  Pre-key MUST be signed by the identity key.
    // @@protoc_insertion_point(field:xmtp.message_contents.PublicKeyBundle.pre_key)
    pub pre_key: ::protobuf::MessageField<PublicKey>,
    // special fields
    // @@protoc_insertion_point(special_field:xmtp.message_contents.PublicKeyBundle.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PublicKeyBundle {
    fn default() -> &'a PublicKeyBundle {
        <PublicKeyBundle as ::protobuf::Message>::default_instance()
    }
}

impl PublicKeyBundle {
    pub fn new() -> PublicKeyBundle {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, PublicKey>(
            "identity_key",
            |m: &PublicKeyBundle| { &m.identity_key },
            |m: &mut PublicKeyBundle| { &mut m.identity_key },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, PublicKey>(
            "pre_key",
            |m: &PublicKeyBundle| { &m.pre_key },
            |m: &mut PublicKeyBundle| { &mut m.pre_key },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PublicKeyBundle>(
            "PublicKeyBundle",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PublicKeyBundle {
    const NAME: &'static str = "PublicKeyBundle";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.identity_key)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pre_key)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.identity_key.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.pre_key.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.identity_key.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.pre_key.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PublicKeyBundle {
        PublicKeyBundle::new()
    }

    fn clear(&mut self) {
        self.identity_key.clear();
        self.pre_key.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PublicKeyBundle {
        static instance: PublicKeyBundle = PublicKeyBundle {
            identity_key: ::protobuf::MessageField::none(),
            pre_key: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PublicKeyBundle {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PublicKeyBundle").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PublicKeyBundle {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PublicKeyBundle {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n!message_contents/public_key.proto\x12\x15xmtp.message_contents\x1a\
    \x20message_contents/signature.proto\"\xe3\x01\n\x11UnsignedPublicKey\
    \x12\x1d\n\ncreated_ns\x18\x01\x20\x01(\x04R\tcreatedNs\x12w\n\x16secp25\
    6k1_uncompressed\x18\x03\x20\x01(\x0b2>.xmtp.message_contents.UnsignedPu\
    blicKey.Secp256k1UncompressedH\0R\x15secp256k1Uncompressed\x1a-\n\x15Sec\
    p256k1Uncompressed\x12\x14\n\x05bytes\x18\x01\x20\x01(\x0cR\x05bytesB\
    \x07\n\x05union\"n\n\x0fSignedPublicKey\x12\x1b\n\tkey_bytes\x18\x01\x20\
    \x01(\x0cR\x08keyBytes\x12>\n\tsignature\x18\x02\x20\x01(\x0b2\x20.xmtp.\
    message_contents.SignatureR\tsignature\"\xa3\x01\n\x15SignedPublicKeyBun\
    dle\x12I\n\x0cidentity_key\x18\x01\x20\x01(\x0b2&.xmtp.message_contents.\
    SignedPublicKeyR\x0bidentityKey\x12?\n\x07pre_key\x18\x02\x20\x01(\x0b2&\
    .xmtp.message_contents.SignedPublicKeyR\x06preKey\"\xa5\x02\n\tPublicKey\
    \x12\x1c\n\ttimestamp\x18\x01\x20\x01(\x04R\ttimestamp\x12C\n\tsignature\
    \x18\x02\x20\x01(\x0b2\x20.xmtp.message_contents.SignatureH\x01R\tsignat\
    ure\x88\x01\x01\x12o\n\x16secp256k1_uncompressed\x18\x03\x20\x01(\x0b26.\
    xmtp.message_contents.PublicKey.Secp256k1UncompressedH\0R\x15secp256k1Un\
    compressed\x1a-\n\x15Secp256k1Uncompressed\x12\x14\n\x05bytes\x18\x01\
    \x20\x01(\x0cR\x05bytesB\x07\n\x05unionB\x0c\n\n_signature\"\x91\x01\n\
    \x0fPublicKeyBundle\x12C\n\x0cidentity_key\x18\x01\x20\x01(\x0b2\x20.xmt\
    p.message_contents.PublicKeyR\x0bidentityKey\x129\n\x07pre_key\x18\x02\
    \x20\x01(\x0b2\x20.xmtp.message_contents.PublicKeyR\x06preKeyBO\n\x1forg\
    .xmtp.proto.message.contentsZ,github.com/xmtp/proto/v3/go/message_conten\
    tsJ\xaa\x10\n\x06\x12\x04\x02\0B\x01\n{\n\x01\x0c\x12\x03\x02\0\x12\x1aq\
    \x20Structure\x20for\x20representing\x20public\x20keys\x20of\x20differen\
    t\x20types,\n\x20including\x20signatures\x20used\x20to\x20authenticate\
    \x20the\x20keys.\n\n\x08\n\x01\x02\x12\x03\x04\0\x1e\n\t\n\x02\x03\0\x12\
    \x03\x06\0*\n\x08\n\x01\x08\x12\x03\x08\0C\n\t\n\x02\x08\x0b\x12\x03\x08\
    \0C\n\x08\n\x01\x08\x12\x03\t\08\n\t\n\x02\x08\x01\x12\x03\t\08\n\x84\
    \x01\n\x02\x04\0\x12\x04\r\0\x1a\x01\x1ax\x20UnsignedPublicKey\x20repres\
    ents\x20a\x20generalized\x20public\x20key,\n\x20defined\x20as\x20a\x20un\
    ion\x20to\x20support\x20cryptographic\x20algorithm\x20agility.\n\n\n\n\
    \x03\x04\0\x01\x12\x03\r\x08\x19\n\x0b\n\x04\x04\0\x02\0\x12\x03\x0e\x04\
    \x1a\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x0e\x04\n\n\x0c\n\x05\x04\0\x02\
    \0\x01\x12\x03\x0e\x0b\x15\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0e\x18\
    \x19\n\x0c\n\x04\x04\0\x08\0\x12\x04\x0f\x04\x11\x05\n\x0c\n\x05\x04\0\
    \x08\0\x01\x12\x03\x0f\n\x0f\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x10\x089\
    \n\x0c\n\x05\x04\0\x02\x01\x06\x12\x03\x10\x08\x1d\n\x0c\n\x05\x04\0\x02\
    \x01\x01\x12\x03\x10\x1e4\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x1078\n4\
    \n\x04\x04\0\x03\0\x12\x04\x16\x04\x19\x05\x1a\x0f\x20EC:\x20SECP256k1\n\
    2\x15\x20Supported\x20key\x20types\n\n\x0c\n\x05\x04\0\x03\0\x01\x12\x03\
    \x16\x0c!\nP\n\x06\x04\0\x03\0\x02\0\x12\x03\x18\x08\x18\x1aA\x20uncompr\
    essed\x20point\x20with\x20prefix\x20(0x04)\x20[\x20P\x20||\x20X\x20||\
    \x20Y\x20],\x2065\x20bytes\n\n\x0e\n\x07\x04\0\x03\0\x02\0\x05\x12\x03\
    \x18\x08\r\n\x0e\n\x07\x04\0\x03\0\x02\0\x01\x12\x03\x18\x0e\x13\n\x0e\n\
    \x07\x04\0\x03\0\x02\0\x03\x12\x03\x18\x16\x17\n\x1e\n\x02\x04\x01\x12\
    \x04\x1d\0\x20\x01\x1a\x12\x20SignedPublicKey\x20\n\n\n\n\x03\x04\x01\
    \x01\x12\x03\x1d\x08\x17\n*\n\x04\x04\x01\x02\0\x12\x03\x1e\x04\x18\"\
    \x1d\x20embeds\x20an\x20UnsignedPublicKey\n\n\x0c\n\x05\x04\x01\x02\0\
    \x05\x12\x03\x1e\x04\t\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x1e\n\x13\n\
    \x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x1e\x16\x17\n\x1e\n\x04\x04\x01\x02\
    \x01\x12\x03\x1f\x04\x1c\"\x11\x20signs\x20key_bytes\n\n\x0c\n\x05\x04\
    \x01\x02\x01\x06\x12\x03\x1f\x04\r\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\
    \x03\x1f\x0e\x17\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x1f\x1a\x1b\nW\
    \n\x02\x04\x02\x12\x04#\0(\x01\x1aK\x20PublicKeyBundle\x20packages\x20th\
    e\x20cryptographic\x20keys\x20associated\x20with\x20a\x20wallet.\n\n\n\n\
    \x03\x04\x02\x01\x12\x03#\x08\x1d\n9\n\x04\x04\x02\x02\0\x12\x03%\x04%\
    \x1a,\x20Identity\x20key\x20MUST\x20be\x20signed\x20by\x20the\x20wallet.\
    \n\n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03%\x04\x13\n\x0c\n\x05\x04\x02\
    \x02\0\x01\x12\x03%\x14\x20\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03%#$\n:\
    \n\x04\x04\x02\x02\x01\x12\x03'\x04\x20\x1a-\x20Pre-key\x20MUST\x20be\
    \x20signed\x20by\x20the\x20identity\x20key.\n\n\x0c\n\x05\x04\x02\x02\
    \x01\x06\x12\x03'\x04\x13\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03'\x14\
    \x1b\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03'\x1e\x1f\n\x86\x01\n\x02\
    \x04\x03\x12\x04.\09\x01\x1ap\x20PublicKey\x20represents\x20a\x20general\
    ized\x20public\x20key,\n\x20defined\x20as\x20a\x20union\x20to\x20support\
    \x20cryptographic\x20algorithm\x20agility.\n2\x08\x20LEGACY\n\n\n\n\x03\
    \x04\x03\x01\x12\x03.\x08\x11\n\x1d\n\x04\x04\x03\x03\0\x12\x040\x043\
    \x05\x1a\x0f\x20The\x20key\x20bytes\n\n\x0c\n\x05\x04\x03\x03\0\x01\x12\
    \x030\x0c!\nP\n\x06\x04\x03\x03\0\x02\0\x12\x032\x08\x18\x1aA\x20uncompr\
    essed\x20point\x20with\x20prefix\x20(0x04)\x20[\x20P\x20||\x20X\x20||\
    \x20Y\x20],\x2065\x20bytes\n\n\x0e\n\x07\x04\x03\x03\0\x02\0\x05\x12\x03\
    2\x08\r\n\x0e\n\x07\x04\x03\x03\0\x02\0\x01\x12\x032\x0e\x13\n\x0e\n\x07\
    \x04\x03\x03\0\x02\0\x03\x12\x032\x16\x17\n\x0b\n\x04\x04\x03\x02\0\x12\
    \x034\x04\x19\n\x0c\n\x05\x04\x03\x02\0\x05\x12\x034\x04\n\n\x0c\n\x05\
    \x04\x03\x02\0\x01\x12\x034\x0b\x14\n\x0c\n\x05\x04\x03\x02\0\x03\x12\
    \x034\x17\x18\n\x0b\n\x04\x04\x03\x02\x01\x12\x035\x04%\n\x0c\n\x05\x04\
    \x03\x02\x01\x04\x12\x035\x04\x0c\n\x0c\n\x05\x04\x03\x02\x01\x06\x12\
    \x035\r\x16\n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x035\x17\x20\n\x0c\n\x05\
    \x04\x03\x02\x01\x03\x12\x035#$\n\x0c\n\x04\x04\x03\x08\0\x12\x046\x048\
    \x05\n\x0c\n\x05\x04\x03\x08\0\x01\x12\x036\n\x0f\n\x0b\n\x04\x04\x03\
    \x02\x02\x12\x037\x089\n\x0c\n\x05\x04\x03\x02\x02\x06\x12\x037\x08\x1d\
    \n\x0c\n\x05\x04\x03\x02\x02\x01\x12\x037\x1e4\n\x0c\n\x05\x04\x03\x02\
    \x02\x03\x12\x03778\n\x9a\x01\n\x02\x04\x04\x12\x04=\0B\x01\x1a\x8d\x01\
    \x20PublicKeyBundle\x20packages\x20the\x20cryptographic\x20keys\x20assoc\
    iated\x20with\x20a\x20wallet,\n\x20both\x20senders\x20and\x20recipients\
    \x20are\x20identified\x20by\x20their\x20key\x20bundles.\n\n\n\n\x03\x04\
    \x04\x01\x12\x03=\x08\x17\n9\n\x04\x04\x04\x02\0\x12\x03?\x04\x1f\x1a,\
    \x20Identity\x20key\x20MUST\x20be\x20signed\x20by\x20the\x20wallet.\n\n\
    \x0c\n\x05\x04\x04\x02\0\x06\x12\x03?\x04\r\n\x0c\n\x05\x04\x04\x02\0\
    \x01\x12\x03?\x0e\x1a\n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03?\x1d\x1e\n:\
    \n\x04\x04\x04\x02\x01\x12\x03A\x04\x1a\x1a-\x20Pre-key\x20MUST\x20be\
    \x20signed\x20by\x20the\x20identity\x20key.\n\n\x0c\n\x05\x04\x04\x02\
    \x01\x06\x12\x03A\x04\r\n\x0c\n\x05\x04\x04\x02\x01\x01\x12\x03A\x0e\x15\
    \n\x0c\n\x05\x04\x04\x02\x01\x03\x12\x03A\x18\x19b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::signature::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(7);
            messages.push(UnsignedPublicKey::generated_message_descriptor_data());
            messages.push(SignedPublicKey::generated_message_descriptor_data());
            messages.push(SignedPublicKeyBundle::generated_message_descriptor_data());
            messages.push(PublicKey::generated_message_descriptor_data());
            messages.push(PublicKeyBundle::generated_message_descriptor_data());
            messages.push(unsigned_public_key::Secp256k1Uncompressed::generated_message_descriptor_data());
            messages.push(public_key::Secp256k1Uncompressed::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
