block-beta
    columns 4
    block:group1:2
       columns 2
       Android LibXMTP
    end   
    space:2
 
    block:group3:2
       columns 2
       React C["LibXMTP"]
    end 
    space
    Node["XMTP Node"]
    block:group2:2
       columns 2
       iOS B["LibXMTP"]
    end
    group1-->Node  
    Node-->group1
    group2-->Node
    Node-->group2
    group3-->Node
    Node-->group3