sequenceDiagram
    participant Alice
    participant Bob
    participant LibXMTP
    participant Node

    Note left of Alice: Send Message
    Alice->>LibXMTP: group.send("Hello, group!")
    LibXMTP->>Node: send-group-messages(SEND_MESSAGE:"Hello, group!")

    Note left of Alice: Receive Message
    Bob->>LibXMTP: group.sync()
    LibXMTP->>Node: query-group-messages(group_id)
    Node-->>LibXMTP: "Alice: Hello, group!"
    Bob->>LibXMTP: group.find_messages()
    LibXMTP-->>Bob: "Alice: Hello, group!"