sequenceDiagram
    participant Alice
    participant Bob
    participant Charlie
    participant LibXMTP
    participant Node

    Note left of Alice: Send Message
    Alice->>LibXMTP: group.send("Hello, group!")
    LibXMTP->>Node: send-group-messages(SEND_MESSAGE:"Hello, group!")

    Note left of Alice: Receive Message
    Bob->>+LibXMTP: group.messages()
    LibXMTP->>+Node: query-group-messages(group_id)
    Node-->>-LibXMTP: "Hello, group!"
    LibXMTP->>-Bob: "Hello, group!"