plugin.com.android.application=8.10.1
plugin.com.android.library=8.10.1
plugin.org.jetbrains.kotlin.android=2.2.20
plugin.org.jetbrains.kotlin.multiplatform=2.2.20
plugin.org.jetbrains.kotlin.plugin.compose=2.2.20
plugin.org.jetbrains.compose=1.8.2
plugin.io.github.gradle-nexus.publish-plugin=1.2.0
plugin.org.jetbrains.dokka=2.2.0
plugin.com.diffplug.spotless=8.0.0
ktlint=1.8.0
desugar=2.1.5
