name: Test Workspace
on:
  workflow_call:
jobs:
  test:
    name: Test (Rust Workspace)
    runs-on: blacksmith-16vcpu-ubuntu-2404
    timeout-minutes: 30
    env:
      SQLX_OFFLINE: "true"
      DATABASE_URL: postgres://xmtp:xmtp@localhost:55432/xmtp_backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          disk-key: rust
          docker-builder: "true"
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: "false"
      - uses: taiki-e/install-action@just
      - name: Check ephemeral backend build boundaries
        run: dev/check-ephemeral-backend
      - name: Start backend
        run: just backend up
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
      - name: Run workspace tests with coverage
        # use `nix build` instead of `nix flake check` because we need the resulting coverage
        run: |
          nix build .#nextest.x86_64-linux --out-link workspace-tests --option sandbox relaxed
      - name: Warm sticky disk with build deps
        run: dev/ci/warm-deps .#nextest.x86_64-linux
      - name: Upload coverage
        uses: codecov/codecov-action@v6
        with:
          files: workspace-tests/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
