name: Test Workspace
on:
  workflow_call:
env:
  NIX_DEVSHELL: rust
  CARGO_TEST_CMD: "cargo llvm-cov nextest --no-fail-fast --no-report"
jobs:
  test:
    name: Test (Rust Workspace)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          sccache: "false"
          with-warpbuild-cache: "false"
      - uses: taiki-e/install-action@just
      - name: Start backend
        run: just backend up
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
      - name: Run tests (v3 + d14n with coverage)
        # use `nix build` instead of `nix flake check` because we need the resulting coverage
        run: nix build -L .#nextest.x86_64-linux.v3 .#nextest.x86_64-linux.d14n

      - name: merge coverage files
        run: nix run nixpkgs#lcov -- --add-tracefile result/coverage --add-tracefile result-1/coverage --output-file lcov.info
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
